version: '3'

services:
  app:
    container_name: framework-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8088:80
    networks:
      - network
  db:
    container_name: framework-db
    restart: unless-stopped
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
    networks:
      - network
  phpmyadmin:
    container_name: framework-phpmyadmin
    restart: unless-stopped
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - 8880:80
    networks:
      - network
networks:
  network:
    driver: bridge